//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public int id { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<decimal> puntuacion { get; set; }
        public Nullable<System.DateTime> fecha_calificacion { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual materias materias { get; set; }
    }
}
