//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamentos
    {
        public int id { get; set; }
        public string nombre_departamento { get; set; }
        public string descripcion { get; set; }
        public string ubicacion { get; set; }
    }
}
