//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripciones
    {
        public int id { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public string estado { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual materias materias { get; set; }
    }
}
